AWSTemplateFormatVersion: '2010-09-09'
Description: 'Resources template for One Bite Pizza Reviews'

Parameters:

  ProjectName:
    Type: String
    Description: "Project name"


Resources:
  OneBitePizzaReviewsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  OneBitePizzaReviewsECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}

Outputs:
  BucketName:
    Description: Name of the bucket
    Value: !Ref OneBitePizzaReviewsBucket
  RepositoryName:
    Description: Name of the repository
    Value: !Ref OneBitePizzaReviewsECRRepository