AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 template for One Bite Pizza Reviews'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: "Deployment environment"

  ProjectName:
    Type: String
    Description: "Project name"


Resources:
  OneBitePizzaReviewsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-${Environment}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  OneBitePizzaReviewsECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-${Environment}

Outputs:
  BucketName:
    Description: Name of the bucket
    Value: !Ref OneBitePizzaReviewsBucket
  RepositoryName:
    Description: Name of the bucket
    Value: !Ref OneBitePizzaReviewsECRRepository