name: ci_workflow
on:
  push:
    branches-ignore:
      - main

env:
    # pass in the start and end date for the most recent days
    START_DATE: $(date -d "2 days ago" +'%Y-%m-%d')
    END_DATE: $(date -d "1 day ago" +'%Y-%m-%d')
    ENV: ci
    GITHUB_SHA: ${{ github.sha }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configure AWS creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region:            us-east-1
            
            - name: Get commit SHA
              run: echo "${GITHUB_SHA}" 

            - name: Create .env file
              run: |
                echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
                echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
                echo "AWS_DEFAULT_REGION=us-east-1" >> .env
                echo "ENV=${ENV}" >> .env
                echo "GITHUB_SHA=${GITHUB_SHA}" >> .env

            # This builds the image and runs the script
            - name: Run test one bite pizza reviews script
              env:
                  ENV: ${{ env.ENV }}
              run: ./scripts/docker/run.sh extract/main.py --start_date ${{ env.START_DATE }} --end_date ${{ env.END_DATE }}

            - name: Push image to ECR
              run: ./scripts/docker/push.sh