name: ci_workflow
on: push

env:
    # pass in the start and end date for the most recent days
    START_DATE: $(date -d "2 days ago" +'%Y-%m-%d')
    END_DATE: $(date -d "1 day ago" +'%Y-%m-%d')
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    ENV: ci

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # This builds the image and runs the script
            - name: Run test one bite pizza reviews script
              run: ./scripts/docker/run.sh extract/main.py --start_date ${{ env.START_DATE }} --end_date ${{ env.END_DATE }}