name: run_prod_script
on:
    schedule:
      - cron: "10 10 * * *"   # Every day at 10:10am
    workflow_dispatch: {}     # allow manual runs

env:
    # pass in the start and end date for the most recent day
    # These are the same in prod because we are running this for every day
    START_DATE: $(date +'%Y-%m-%d')
    END_DATE: $(date +'%Y-%m-%d')   
    ENV: prod

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            - name: Configure AWS creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region:            us-east-1

            - name: Log in to ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Install dependencies
              run: uv sync

            - name: Run script
              env:
                ENV: ${{ env.ENV }}
              run: uv run app/main.py --start_date ${{ env.START_DATE }} --end_date ${{ env.END_DATE }}
