name: test
on: push

env:
    START_DATE: $(date -d "3 days" +'%Y-%m-%d')
    END_DATE: $(date -d "1 day" +'%Y-%m-%d')
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                version: 0.6.14

            - name: Install dependencies
              run: uv sync

            - name: Lint files
              run: uvx ruff check

            - name: Run script
              
              run: uv run main.py --start_date ${{ env.START_DATE }} --end_date ${{ env.END_DATE }}
